
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    env_file:
      - .env
    environment:
      ACCEPT_EULA: Y
      MSSQL_PID: Express
    ports:
      - '1433:1433'
    networks:
      - app-network
    volumes:
      - ./data:/var/opt/mssql/data
    platform: linux/amd64

  identity-app-rest-api:
    container_name: "rest-api"
    build:
      context: .
      dockerfile: ./Api/Dockerfile
    depends_on:
      - sql-server
    ports:
      - '5186:5186'
    networks:
      - app-network
    environment:
      - ConnectionStrings__DefaultConnection = ${MSSQL_STRING_CONNECTION}

networks:
  app-network:
    driver: bridge
